### ISSUE TITLE
[FEATURE] 채팅 방 입장 시 채팅 내용 로드, 시간 표시 등 채팅 방 내 상세한 부분 구현

### ISSUE THREAD

**Issue by ywonchae1** [Piro-Pirot/django-pirot#20]
## 📢 이슈 내용
지금 너무 못생겼어 이대로 가다가는 석류님과 선우님께 몰매를 맞는다!
## 📃 상세 내용
- 데이터 가공
## ✔️ 체크리스트
- [ ] 채팅 내용 로드할 때 페이지네이션이 필요할지,,
- [ ] 내 채팅은 오른쪽에 보이게 하기
- [ ] 채팅 created_at 시간 보이기

**Comment by pomiryu** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ
